# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  buildConfiguration: Release

jobs:
- job: Build_and_Test
  strategy:
    matrix:
      linux:
        vmImage: ubuntu-latest
      macos:
        vmImage: macOS-latest
      windows:
        vmImage: windows-latest
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Sdk 10.0'
    inputs:
      version: 10.x
    displayName: 'dotnet build'
  - script: dotnet build -c $(buildConfiguration) -v n
  - displayName: 'dotnet test'
    script: |
      dotnet test -c $(buildConfiguration) --no-build --project ./test/Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj
      dotnet test -c $(buildConfiguration) --no-build --project ./test/Xunit.DependencyInjection.Test.AspNetCore/Xunit.DependencyInjection.Test.AspNetCore.csproj
      dotnet test -c $(buildConfiguration) --no-build --project ./test/Xunit.DependencyInjection.Test.DisableTestParallelization/Xunit.DependencyInjection.Test.DisableTestParallelization.csproj
      dotnet test -c $(buildConfiguration) --no-build --project ./test/Xunit.DependencyInjection.Test.FSharp/Xunit.DependencyInjection.Test.FSharp.fsproj
      dotnet test -c $(buildConfiguration) --no-build --project ./test/Xunit.DependencyInjection.Test.Parallelization/Xunit.DependencyInjection.Test.Parallelization.csproj
